// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndahuzihvcqhuocamljz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kYWh1emlodmNxaHVvY2FtbGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MjAyNjksImV4cCI6MjA3MzM5NjI2OX0.YNybDc4MDrZLBS_xl9GEuhPXxVDkEUj3f_HnVvHxLHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});